language: R
cache:
  packages: true
  directories:
    - docs

addons:
  apt:
    packages:
      - libxml2-dev

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script: netlify deploy --prod --dir docs
  skip_cleanup: true
