language: R
sudo: required
cache: packages

r_packages:
  - bookdown
  - covr

deploy:
  provider: pages                  # Specify the gh-pages deployment method
  skip_cleanup: true               # Don't remove files
  github_token: $GITHUB_TOKEN      # Set in travis-ci.org dashboard
  local_dir: docs                  # Deploy the docs folder
  target_branch: master

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

after_success:
  - Rscript -e 'covr::codecov()'
